### ISSUE TITLE
Bug for StackFrame

### ISSUE THREAD

**Issue by ehaerim** [rioki/rex#1]
struct StackFrame
    {
        DWORD64 address;
        std::string name;
        std::string module;
        unsigned int line;
        std::string file;
    };

should be

	struct StackFrame
	{
**#if defined(_WIN64)
		DWORD64 address;
#else // _WIN64
		DWORD address;
#endif // _WIN64**
		std::string name;
		std::string module;
		unsigned int line;
		std::string file;
	};

Please confirm.

**Comment by ehaerim** [comment]
Why skip the first call?

			if (!first) // why skip the first level call?
			{ 
				frames.push_back(f);
			}
			first = false;

**Comment by rioki** [comment]
About the first issue, although the address on a 32 bit system is a DWORD, there is little loss with a DWORD64. Those 4 extra bytes per stack frame are not going to matter much. If you really feel touchy about it you can create a PR.

About the second issue. It's ignoring the stack_trace function. It would be kind of stupid if the stack trace function would include itself.
